export const SEARCH_PHOTOS = 'SEARCH_PHOTOS';
export const FETCH_SEARCH_PHOTOS = 'FETCH_SEARCH_PHOTOS';
export const FETCH_RANDOM_PHOTOS = 'FETCH_RANDOM_PHOTOS';

export const GET_PHOTO_MODAL = 'GET_PHOTO_MODAL';
export const REMOVE_PHOTO_MODAL = 'REMOVE_PHOTO_MODAL';
